Repository infection/infection, pull requests merged in 2018-07, with the labels that each got.

#405 BadgeLogger now reports exact errors
  src/Http/BadgeApiClient.php
  src/Logger/BadgeLogger.php
  tests/Logger/BadgeLoggerTest.php
Labels: enhancement

#385 Improve errors that could be generated while mutating or parsing
  src/Exception/InvalidMutatorException.php
  src/Mutant/Exception/ParserException.php
  src/Mutant/Generator/MutationsGenerator.php
  src/Visitor/MutationsCollectorVisitor.php
  tests/Exception/InvalidMutatorExceptionTest.php
  tests/Fixtures/Autoloaded/Mutator/ErrorMutator.php
  tests/Fixtures/Files/InvalidFile/InvalidFile.php
  tests/Mutant/Exception/ParserExceptionTest.php
  tests/Mutant/Generator/MutationsGeneratorTest.php
Labels: Needs Review

#390 Show time and memory info to the console output
  composer.json
  composer.lock
  src/Command/InfectionCommand.php
  src/Console/InfectionContainer.php
  src/Events/ApplicationExecutionFinished.php
  src/Events/ApplicationExecutionStarted.php
  src/Performance/Listener/PerformanceLoggerSubscriber.php
  src/Performance/Memory/MemoryFormatter.php
  src/Performance/Time/TimeFormatter.php
  src/Performance/Time/Timer.php
  src/Process/Builder/SubscriberBuilder.php
  tests/Events/ApplicationExecutionFinishedTest.php
  tests/Events/ApplicationExecutionStartedTest.php
  tests/Performance/Listener/PerformanceLoggerSubscriberTest.php
  tests/Performance/Memory/MemoryFormatterTest.php
  tests/Performance/Time/TimeFormatterTest.php
  tests/Performance/Time/TimerTest.php
  tests/Process/Builder/SubscriberBuilderTest.php
Labels: Needs Review, feature

#423 Fix exclude to excludes for generated config file
  src/Command/ConfigureCommand.php
Labels: bug

#424 Sort logs
  src/Logger/DebugFileLogger.php
  src/Logger/FileLogger.php
  src/Logger/TextFileLogger.php
  src/Process/MutantProcess.php
  src/Process/MutantProcessInterface.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixtures/e2e/Config_Framework/expected-output.txt
  tests/Fixtures/e2e/Multiline_Statement/expected-output.txt
  tests/Fixtures/e2e/Trait_Coverage/expected-output.txt
  tests/Logger/DebugFileLoggerTest.php
  tests/Logger/SummaryFileLoggerTest.php
  tests/Logger/TextFileLoggerTest.php
  tests/Process/MutantProcessTest.php
Labels: enhancement
