Repository infection/infection, pull requests merged in 2018-10, with the labels that each got.

#497 Update phpstan to 10.3
  Makefile
Labels: Needs Review

#495 Align file naming
  phpunit.xml.dist
Labels: Needs Review

#472 Find php script from .bat file on Windows
  src/Finder/TestFrameworkFinder.php
  tests/Finder/MockVendor.php
  tests/Finder/TestFrameworkFinderTest.php
Labels: Needs Review, enhancement

#513 Implement UnwrapArrayMap and UnwrapArrayFilter mutators
  src/Mutator/Unwrap/AbstractUnwrapMutator.php
  src/Mutator/Unwrap/UnwrapArrayFilter.php
  src/Mutator/Unwrap/UnwrapArrayMap.php
  src/Mutator/Util/MutatorProfile.php
  tests/Mutator/Unwrap/UnwrapArrayFilterTest.php
  tests/Mutator/Unwrap/UnwrapArrayMapTest.php
Labels: new mutator

#485 Fix Decrement integer
  src/Mutator/Boolean/FalseValue.php
  src/Mutator/Boolean/TrueValue.php
  src/Mutator/Number/DecrementInteger.php
  src/Mutator/Regex/PregMatchMatches.php
  src/Mutator/Regex/PregQuote.php
  src/Mutator/Removal/FunctionCallRemoval.php
  tests/Mutator/Number/DecrementIntegerTest.php
Labels: Needs Review

#527 Enhancement: Implement UnwrapArrayReverse mutator
  src/Mutator/Unwrap/UnwrapArrayReverse.php
  src/Mutator/Util/MutatorProfile.php
  tests/Mutator/Unwrap/UnwrapArrayReverseTest.php
Labels: new mutator

#529 Enhancement: Implement UnwrapArrayFlip mutator
  src/Mutator/Unwrap/UnwrapArrayFlip.php
  src/Mutator/Util/MutatorProfile.php
  tests/Mutator/Unwrap/UnwrapArrayFlipTest.php
Labels: new mutator
