Repository infection/infection, pull requests merged in 2018-08, with the labels that each got.

#383 Introduce PregMatchMatches mutator
  src/Mutator/Regex/PregMatchMatches.php
  src/Mutator/Util/MutatorProfile.php
  tests/Fixtures/Autoloaded/RegexMatchMatches/ReturnNotAllowed.php
  tests/Fixtures/Autoloaded/RegexMatchMatches/ReturnTypes.php
  tests/Mutator/Regex/PregMatchMatchesTest.php
Labels: new mutator

#454 Rename infection-log.txt -> infection.log
  .gitignore
  infection.json.dist
  src/Config/ValueProvider/TextLogFileProvider.php
  tests/Console/E2ETest.php
  tests/Fixtures/e2e/.gitignore
  tests/Fixtures/e2e/Config_Bootstrap/infection.json
  tests/Fixtures/e2e/Config_Bootstrap/run_tests.bash
  tests/Fixtures/e2e/Config_Framework/infection.json
  tests/Fixtures/e2e/Configure/infection.json.test
  tests/Fixtures/e2e/Custom_tmp_dir/infection.json
  tests/Fixtures/e2e/Empty_Path/infection.json
  tests/Fixtures/e2e/Empty_Path/run_tests.bash
  tests/Fixtures/e2e/Example_Test/infection.json
  tests/Fixtures/e2e/Exec_Path/infection.json
  tests/Fixtures/e2e/Exec_Path/run_tests.bash
  tests/Fixtures/e2e/Identical_Mutator_Example/infection.json
  tests/Fixtures/e2e/Ignore_MSI_Zero_Mutations/infection.json
  tests/Fixtures/e2e/Ignore_MSI_Zero_Mutations/run_tests.bash
  tests/Fixtures/e2e/Memory_Limit/infection.json
  tests/Fixtures/e2e/Memory_Limit/run_tests.bash
  tests/Fixtures/e2e/Multiline_Statement/infection.json.dist
  tests/Fixtures/e2e/PHPUnit_Custom_Config_Dir/infection.json
  tests/Fixtures/e2e/Parameters_Coverage/infection.json
  tests/Fixtures/e2e/Phpunit_Bat_Wrapper/infection.json
  tests/Fixtures/e2e/Phpunit_Bat_Wrapper/run_tests.bash
  tests/Fixtures/e2e/Profiles_Ignore_Combination/infection.json
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection.json
  tests/Fixtures/e2e/Provide_Existing_Coverage/run_tests.bash
  tests/Fixtures/e2e/README.md
  tests/Fixtures/e2e/Save_PHPUnit_Bootstrap_File/infection.json
  tests/Fixtures/e2e/Test_Frameworks/infection.json
  tests/Fixtures/e2e/Test_Frameworks/run_tests.bash
  tests/Fixtures/e2e/Trait_Coverage/infection.json
  tests/Fixtures/e2e/standard_script.bash
  tests/Process/Listener/MutationTestingResultsLoggerSubscriberTest.php
Labels: Needs Review

#440 Improve compatibility with framework based applications
  src/Command/InfectionCommand.php
  tests/Fixtures/e2e/Config_Bootstrap/src/bootstrap.php
Labels: Needs Review, bug

#462 Use default test framework if neither CLI nor config has the value for it
  src/Command/InfectionCommand.php
  tests/Fixtures/e2e/Configure/do_configure.expect
Labels: bug

#458 Validate that infection.json contains valid (writable) file paths for loggers
  composer.json
  composer.lock
  src/Config/Validator.php
  src/Console/InfectionContainer.php
  src/Logger/FileLogger.php
  src/Process/Listener/MutationTestingResultsLoggerSubscriber.php
  tests/Config/ValidatorTest.php
  tests/Logger/DebugFileLoggerTest.php
  tests/Logger/PerMutatorLoggerTest.php
  tests/Logger/SummaryFileLoggerTest.php
  tests/Logger/TextFileLoggerTest.php
Labels: Needs Review, bug
