Repository infection/infection, pull requests merged in 2018-09, with the labels that each got.

#470 Fix .bat files being invoked with php
  src/TestFramework/AbstractTestFrameworkAdapter.php
Labels: bug, in progress

#475 Reduce docker images size
  devTools/Dockerfile-php71-xdebug
  devTools/Dockerfile-php72-xdebug
Labels: Needs Review

#476 Add config for automatic tap release
  .github/tap-release.yml
Labels: Needs Review

#474 Update xdebug-handler to simplify sub-processes
  composer.json
  composer.lock
  src/Console/Application.php
  src/Console/Util/PhpProcess.php
Labels: Needs Review

#468 Remove empty option from test framework arguments
  src/TestFramework/PhpSpec/CommandLine/ArgumentsAndOptionsBuilder.php
  src/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilder.php
  tests/TestFramework/PhpSpec/CommandLine/ArgumentsAndOptionsBuilderTest.php
  tests/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilderTest.php
Labels: Needs Review, in progress

#479 Change foreach to array_map and add return types
  src/Differ/DiffColorizer.php
  src/Differ/Differ.php
Labels: Needs Review

#481 Exclude --testsuite from PhpUnit options except for initial process
  src/TestFramework/PhpUnit/PhpUnitExtraOptions.php
  tests/TestFramework/PhpUnit/PhpUnitExtraOptionsTest.php
Labels: Needs Review

#483 Extend TestFrameworkExtraOptions to cover more complex usages of options
  src/TestFramework/TestFrameworkExtraOptions.php
  tests/TestFramework/PhpUnit/PhpUnitExtraOptionsTest.php
Labels: Needs Review

#487 Validate phpunit.xml
  composer.json
  composer.lock
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpUnit/Config/Exception/InvalidPhpUnitXmlConfigException.php
  src/TestFramework/PhpUnit/Config/XmlConfigurationHelper.php
  tests/TestFramework/PhpUnit/Config/Exception/InvalidPhpUnitXmlConfigExceptionTest.php
  tests/TestFramework/PhpUnit/Config/XmlConfigurationHelperTest.php
Labels: Needs Review

#450 [RFC] Yield mutations
  .travis.yml
  src/Mutation.php
  src/MutationInterface.php
  src/Mutator/Arithmetic/BitwiseNot.php
  src/Mutator/Arithmetic/Increment.php
  src/Mutator/Arithmetic/RoundingFamily.php
  src/Mutator/Removal/FunctionCallRemoval.php
  src/Mutator/Removal/MethodCallRemoval.php
  src/Mutator/ReturnValue/FunctionCall.php
  src/Mutator/ReturnValue/NewObject.php
  src/Mutator/Util/Mutator.php
  src/Mutator/Util/MutatorProfile.php
  src/Visitor/MutationsCollectorVisitor.php
  src/Visitor/MutatorVisitor.php
  tests/AutoReview/ProjectCodeTest.php
  tests/Fixtures/SimpleMutation.php
  tests/Fixtures/SimpleMutationsCollectorVisitor.php
  tests/Fixtures/SimpleMutatorVisitor.php
  tests/MutationTest.php
  tests/Mutator/AbstractMutatorTestCase.php
  tests/Mutator/Arithmetic/AssignmentTest.php
  tests/Mutator/Arithmetic/DivisionTest.php
  tests/Mutator/Arithmetic/RoundingFamilyTest.php
  tests/Mutator/Arithmetic/ShiftRightTest.php
  tests/Mutator/Boolean/ArrayItemTest.php
  tests/Mutator/Boolean/IdenticalEqualTest.php
  tests/Mutator/Boolean/NotIdenticalNotEqualTest.php
  tests/Mutator/Cast/CastBoolTest.php
  tests/Mutator/Cast/CastFloatTest.php
  tests/Mutator/Cast/CastIntTest.php
  tests/Mutator/FunctionSignature/PublicVisibilityTest.php
  tests/Mutator/Removal/FunctionCallRemovalTest.php
  tests/Mutator/Removal/MethodCallRemovalTest.php
  tests/Mutator/ReturnValue/FunctionCallTest.php
  tests/Mutator/ReturnValue/IntegerNegationTest.php
  tests/TestFramework/Coverage/CodeCoverageDataTest.php
  tests/Visitor/MutatorVisitorTest.php
Labels: Needs Review, RFC, new mutator

#391 Add counterparts to identical mutator and remove them from default
  .travis.yml
  src/Mutator/Boolean/EqualIdentical.php
  src/Mutator/Boolean/NotEqualNotIdentical.php
  src/Mutator/Util/MutatorProfile.php
  tests/Fixtures/e2e/Config_Framework/expected-output.txt
  tests/Fixtures/e2e/Identical_Mutator_Example/infection.json
  tests/Fixtures/e2e/Parameters_Coverage/expected-output.txt
  tests/Fixtures/e2e/Provide_Existing_Coverage/expected-output_phpspec.txt
  tests/Fixtures/e2e/Provide_Existing_Coverage/expected-output_phpunit.txt
  tests/Fixtures/e2e/Test_Frameworks/expected-output.txt
  tests/Mutator/Boolean/EqualIdenticalTest.php
  tests/Mutator/Boolean/NotEqualNotIdenticalTest.php
Labels: Needs Review, new mutator
