Repository infection/infection, pull requests merged in 2018-02, with the labels that each got.

#176 Use existing coverage reports
  .travis.yml
  app/container.php
  src/Command/InfectionCommand.php
  src/Console/Application.php
  src/Process/Builder/ProcessBuilder.php
  src/Process/Listener/MutationTestingConsoleLoggerSubscriber.php
  src/Process/Runner/InitialTestsRunner.php
  src/TestFramework/Coverage/CoverageDoesNotExistException.php
  src/TestFramework/Factory.php
  src/TestFramework/PhpSpec/Config/AbstractYamlConfiguration.php
  src/TestFramework/PhpSpec/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpSpec/Config/InitialYamlConfiguration.php
  src/TestFramework/PhpSpec/Config/MutationYamlConfiguration.php
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpUnit/Coverage/CoverageXmlParser.php
  src/TestFramework/PhpUnit/Coverage/PhpUnitTestFileDataProvider.php
  tests/Fixtures/e2e/Provide_Existing_Coverage/README.md
  tests/Fixtures/e2e/Provide_Existing_Coverage/composer.json
  tests/Fixtures/e2e/Provide_Existing_Coverage/expected-output.txt
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection-coverage/coverage-xml/SourceClass.php.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection-coverage/coverage-xml/index.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection-coverage/phpspec-coverage-xml/SourceClass.php.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection-coverage/phpspec-coverage-xml/index.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection-coverage/phpunit.junit.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/infection.json
  tests/Fixtures/e2e/Provide_Existing_Coverage/phpspec.yml
  tests/Fixtures/e2e/Provide_Existing_Coverage/phpunit.xml
  tests/Fixtures/e2e/Provide_Existing_Coverage/run_tests.bash
  tests/Fixtures/e2e/Provide_Existing_Coverage/spec/SourceClassSpec.php
  tests/Fixtures/e2e/Provide_Existing_Coverage/src/SourceClass.php
  tests/Fixtures/e2e/Provide_Existing_Coverage/tests/SourceClassTest.php
  tests/Fixtures/e2e/Test_Frameworks/run_tests.bash
  tests/Fixtures/e2e/standard_script.bash
  tests/Process/Builder/ProcessBuilderTest.php
  tests/Process/Runner/InitialTestsRunnerTest.php
  tests/TestFramework/FactoryTest.php
  tests/TestFramework/PhpSpec/Config/Builder/InitialConfigBuilderTest.php
  tests/TestFramework/PhpSpec/Config/InitialYamlConfigurationTest.php
  tests/TestFramework/PhpSpec/Config/MutationYamlConfigurationTest.php
  tests/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilderTest.php
  tests/e2e_tests
Labels: feature

#186 Fix performance issue in SourceFilesFinder
  .travis.yml
  src/Finder/Iterator/RealPathFilterIterator.php
  src/Finder/SourceFilesFinder.php
Labels: performance

#191 Allow coverage of function signatures of traits
  src/TestFramework/PhpUnit/Coverage/CoverageXmlParser.php
  tests/Fixtures/Files/phpunit/coverage-xml/FirstLevel/SecondLevel/secondLevelTrait.php
  tests/Fixtures/Files/phpunit/coverage-xml/FirstLevel/SecondLevel/secondLevelTrait.php.xml
  tests/Fixtures/Files/phpunit/coverage-xml/index.xml
  tests/Fixtures/e2e/Trait_Coverage/README.md
  tests/Fixtures/e2e/Trait_Coverage/composer.json
  tests/Fixtures/e2e/Trait_Coverage/expected-output.txt
  tests/Fixtures/e2e/Trait_Coverage/infection.json
  tests/Fixtures/e2e/Trait_Coverage/phpunit.xml
  tests/Fixtures/e2e/Trait_Coverage/src/SourceClass.php
  tests/Fixtures/e2e/Trait_Coverage/src/SourceTrait.php
  tests/Fixtures/e2e/Trait_Coverage/tests/SourceClassTest.php
  tests/TestFramework/PhpUnit/Coverage/CoverageXmlParserTest.php
Labels: bug, enhancement
