Repository infection/infection, pull requests merged in 2019-09, with the labels that each got.

#781 Use xdebug-filter to reduce the time needed to collect coverage
  .gitignore
  .travis.yml
  appveyor.yml
Labels: enhancement

#787 Mutate `mb_str_split` to `str_split`
  src/Mutator/Extensions/MBString.php
  tests/phpunit/Mutator/Extensions/MBStringTest.php
Labels: new mutator

#784 [RFC] Mutator: Spread operator in Array Expression - leave only the first element
  src/Mutator/Operator/Spread.php
  src/Mutator/Util/MutatorProfile.php
  tests/phpunit/Mutator/Operator/SpreadTest.php
Labels: Needs Review, RFC, new mutator

#790 Fix: Run 'make cs'
  .gitignore
Labels: bug

#791 Deactivate stderr redirection in phpunit.xml
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpUnit/Config/Builder/MutationConfigBuilder.php
  src/TestFramework/PhpUnit/Config/XmlConfigurationHelper.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationHelperTest.php
Labels: bugfix
