Repository infection/infection, pull requests merged in 2019-03, with the labels that each got.

#649 #597 Array item removal mutator
  resources/schema.json
  src/Mutator/Removal/ArrayItemRemoval.php
  src/Mutator/Util/MutatorProfile.php
  tests/Mutator/Removal/ArrayItemRemovalTest.php
Labels: Needs Review, new mutator

#660 Preventing Issue Where Extra Commas Caused Infection To Ignore Filter
  src/Finder/SourceFilesFinder.php
  tests/Finder/SourceFilesFinderTest.php
Labels: bugfix

#663 Adding Line Numbers To Mutator Ignore List
  infection.json.dist
  src/Mutator/Util/Mutator.php
  src/Mutator/Util/MutatorConfig.php
  tests/Mutator/Util/MutatorConfigTest.php
Labels: enhancement

#673 Do not mutate * to / and vice versa if one of the operands is numeric ±1.0
  src/Mutator/Arithmetic/Division.php
  src/Mutator/Arithmetic/Multiplication.php
  tests/Mutator/Arithmetic/DivisionTest.php
  tests/Mutator/Arithmetic/MultiplicationTest.php
Labels: Needs Review

#651 Use new config data when Infection has been executed at the first time
  src/Command/InfectionCommand.php
  src/Config/InfectionConfig.php
  src/Json/JsonFile.php
  tests/Fixtures/e2e/Initial_Configuration/.gitignore
  tests/Fixtures/e2e/Initial_Configuration/Initial_Configuration/SourceClass.php
  tests/Fixtures/e2e/Initial_Configuration/composer.json
  tests/Fixtures/e2e/Initial_Configuration/do_configure.expect
  tests/Fixtures/e2e/Initial_Configuration/phpunit.xml
  tests/Fixtures/e2e/Initial_Configuration/run_tests.bash
  tests/Fixtures/e2e/Initial_Configuration/tests/Initial_Configuration_Test.php
  tests/Json/JsonFileTest.php
Labels: Needs Review, bugfix
