Repository infection/infection, pull requests merged in 2019-01, with the labels that each got.

#594 Enhancement: Implement UnwrapArrayMergeRecursive mutator
  src/Mutator/Unwrap/UnwrapArrayMergeRecursive.php
  src/Mutator/Util/MutatorProfile.php
  tests/Mutator/Unwrap/UnwrapArrayMergeRecursiveTest.php
Labels: new mutator

#595 Guess test framework when symfony/phpunit-bridge is used
  src/Finder/TestFrameworkFinder.php
  tests/Fixtures/e2e/SymfonyBridge/README.md
  tests/Fixtures/e2e/SymfonyBridge/composer.json
  tests/Fixtures/e2e/SymfonyBridge/expected-output.txt
  tests/Fixtures/e2e/SymfonyBridge/infection.json
  tests/Fixtures/e2e/SymfonyBridge/phpunit.xml
  tests/Fixtures/e2e/SymfonyBridge/src/SourceClass.php
  tests/Fixtures/e2e/SymfonyBridge/tests/SourceClassTest.php
  tests/Fixtures/e2e/SymfonyFlex/README.md
  tests/Fixtures/e2e/SymfonyFlex/composer.json
  tests/Fixtures/e2e/SymfonyFlex/expected-output.txt
  tests/Fixtures/e2e/SymfonyFlex/infection.json
  tests/Fixtures/e2e/SymfonyFlex/phpunit.xml
  tests/Fixtures/e2e/SymfonyFlex/src/SourceClass.php
  tests/Fixtures/e2e/SymfonyFlex/tests/SourceClassTest.php
Labels: bugfix

#607 Fixed E2ETest::test_it_runs_an_e2e_test_with_success() for win
  src/Logger/DebugFileLogger.php
  src/Logger/FileLogger.php
  src/Logger/PerMutatorLogger.php
  src/Logger/TextFileLogger.php
  src/StreamWrapper/IncludeInterceptor.php
  tests/Config/InfectionConfigTest.php
  tests/Config/ValueProvider/AbstractBaseProviderTest.php
  tests/Config/ValueProvider/PhpUnitCustomExecutablePathProviderTest.php
  tests/Console/E2ETest.php
  tests/Finder/LocatorTest.php
  tests/Finder/TestFrameworkFinderTest.php
  tests/Logger/DebugFileLoggerTest.php
  tests/Logger/PerMutatorLoggerTest.php
  tests/Logger/SummaryFileLoggerTest.php
  tests/Logger/TextFileLoggerTest.php
  tests/StreamWrapper/IncludeInterceptorTest.php
  tests/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilderTest.php
  tests/TestFramework/PhpUnit/Config/Builder/MutationConfigBuilderTest.php
  tests/TestFramework/PhpUnit/Config/Path/PathReplacerTest.php
Labels: bugfix

#599 Disabling mutating "true" -> "false" in TrueValue mutator for in_array/array_search
  resources/schema.json
  src/Mutator/Boolean/TrueValue.php
  src/Mutator/Util/Mutator.php
  src/Mutator/Util/MutatorConfig.php
  tests/Json/JsonFileTest.php
  tests/Mutator/AbstractMutatorTestCase.php
  tests/Mutator/Boolean/TrueValueTest.php
Labels: Needs Review, feature
