Repository infection/infection, pull requests merged in 2019-07, with the labels that each got.

#686 Fix #672 and same problem for testFrameworkOptions
  src/Command/InfectionCommand.php
  src/Console/InfectionContainer.php
  tests/Console/InfectionContainerTest.php
  tests/Fixtures/e2e/Test_Framework_Options_Config/README.md
  tests/Fixtures/e2e/Test_Framework_Options_Config/composer.json
  tests/Fixtures/e2e/Test_Framework_Options_Config/expected-output.txt
  tests/Fixtures/e2e/Test_Framework_Options_Config/infection.json
  tests/Fixtures/e2e/Test_Framework_Options_Config/phpunit.xml
  tests/Fixtures/e2e/Test_Framework_Options_Config/src/SourceClass.php
  tests/Fixtures/e2e/Test_Framework_Options_Config/tests/SourceClassTest.php
  tests/Fixtures/e2e/Test_PHP_Options_Config/README.md
  tests/Fixtures/e2e/Test_PHP_Options_Config/composer.json
  tests/Fixtures/e2e/Test_PHP_Options_Config/expected-output.txt
  tests/Fixtures/e2e/Test_PHP_Options_Config/infection.json
  tests/Fixtures/e2e/Test_PHP_Options_Config/phpunit.xml
  tests/Fixtures/e2e/Test_PHP_Options_Config/src/SourceClass.php
  tests/Fixtures/e2e/Test_PHP_Options_Config/tests/SourceClassTest.php
Labels: bugfix

#735 Leave only one element in the non empty returned array
  src/Mutator/ReturnValue/ArrayOneItem.php
  src/Mutator/Util/MutatorProfile.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-function-call.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-function-variable-call.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-method-call.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-not-array.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-nullable-array.php
  tests/Fixtures/Autoloaded/ArrayOneItem/does-not-mutate-raw-array.php
  tests/Fixtures/Autoloaded/ArrayOneItem/mutates-not-nullable-array.php
  tests/Mutator/ReturnValue/ArrayOneItemTest.php
Labels: new mutator

#738 Update E2E tests to use PHPUnit 8
  tests/Console/E2ETest.php
  tests/Fixtures/e2e/Code_Coverage_Ignore/composer.json
  tests/Fixtures/e2e/Config_Bootstrap/composer.json
  tests/Fixtures/e2e/Configure/composer.json
  tests/Fixtures/e2e/Custom_tmp_dir/composer.json
  tests/Fixtures/e2e/Empty_Path/composer.json
  tests/Fixtures/e2e/Example_Test/composer.json
  tests/Fixtures/e2e/Exec_Path/composer.json
  tests/Fixtures/e2e/Identical_Mutator_Example/composer.json
  tests/Fixtures/e2e/Ignore_MSI_Zero_Mutations/composer.json
  tests/Fixtures/e2e/Initial_Configuration/composer.json
  tests/Fixtures/e2e/Memory_Limit/composer.json
  tests/Fixtures/e2e/Multiline_Statement/composer.json
  tests/Fixtures/e2e/Multiline_Statement/tests/CalculatorTest.php
  tests/Fixtures/e2e/PHPUnit_Custom_Config_Dir/composer.json
  tests/Fixtures/e2e/PHPUnit_Hidden_Dependency/composer.json
  tests/Fixtures/e2e/PHPUnit_XSD_Validation/composer.json
  tests/Fixtures/e2e/PSR_0_Autoloader/composer.json
  tests/Fixtures/e2e/Parameters_Coverage/composer.json
  tests/Fixtures/e2e/PhpUnit_Depends_Order/composer.json
  tests/Fixtures/e2e/PhpUnit_Depends_Order/expected-output.txt
  tests/Fixtures/e2e/PhpUnit_Depends_Order/tests/SourceClassTest.php
  tests/Fixtures/e2e/Phpunit_Bat_Wrapper/composer.json
  tests/Fixtures/e2e/Profiles_Ignore_Combination/composer.json
  tests/Fixtures/e2e/Provide_Existing_Coverage/composer.json
  tests/Fixtures/e2e/Save_PHPUnit_Bootstrap_File/composer.json
  tests/Fixtures/e2e/Test_Framework_Options_Config/composer.json
  tests/Fixtures/e2e/Test_Frameworks/composer.json
  tests/Fixtures/e2e/Test_PHP_Options_Config/composer.json
  tests/Fixtures/e2e/Trait_Coverage/composer.json
  tests/Fixtures/e2e/UncoveredInterfaces/composer.json
  tests/Fixtures/e2e/Variables_Order_EGPCS/composer.json
Labels: tests fail

#743 Bump the versions used where appropriate
  composer.json
  composer.lock
Labels: Needs Review

#763 Remove type wrap of anyOf to fix invalid JSON schema
  resources/schema.json
Labels: bugfix
