Repository infection/infection, pull requests merged in 2019-11, with the labels that each got.

#821 Allow text logs to be written to a PHP stream
  src/Logger/FileLogger.php
  tests/e2e/Output_Stream/README.md
  tests/e2e/Output_Stream/composer.json
  tests/e2e/Output_Stream/expected-output.txt
  tests/e2e/Output_Stream/infection.json.dist
  tests/e2e/Output_Stream/phpunit.xml
  tests/e2e/Output_Stream/run_tests.bash
  tests/e2e/Output_Stream/src/Example.php
  tests/e2e/Output_Stream/tests/ExampleTest.php
  tests/phpunit/Logger/TextFileLoggerTest.php
Labels: DX, feature

#830 allow to enable pcov with initial-tests-php-options
  src/Process/Coverage/CoverageRequirementChecker.php
  tests/phpunit/Process/Coverage/CoverageRequirementCheckerTest.php
Labels: enhancement

#831 Implement UnwrapStrReplace mutator
  src/Mutator/Unwrap/UnwrapStrReplace.php
  src/Mutator/Util/MutatorProfile.php
  tests/phpunit/Mutator/Unwrap/UnwrapStrReplaceTest.php
Labels: feature, new mutator

#809 Added version number to ASCII banner
  src/Console/Application.php
Labels: DX, enhancement

#846 Make interceptor resilient to file not found warnings
  src/StreamWrapper/IncludeInterceptor.php
  tests/phpunit/StreamWrapper/IncludeInterceptorTest.php
Labels: bugfix

#864 Add 'clone' removal mutator
  resources/schema.json
  src/Mutator/Removal/CloneRemoval.php
  src/Mutator/Util/MutatorProfile.php
  tests/phpunit/Mutator/Removal/CloneRemovalTest.php
Labels: new mutator
