Repository infection/infection, pull requests merged in 2020-04, with the labels that each got.

#1232 InstanceOf_ mutator
  resources/schema.json
  src/Mutator/Boolean/InstanceOf_.php
  src/Mutator/ProfileList.php
  tests/phpunit/Fixtures/SimpleMutationsCollectorVisitor.php
  tests/phpunit/Mutator/Boolean/InstanceOf_Test.php
Labels: Mutator

#1239 Return back `$finder->notPath($excludedDir)` to filter out excluded files configured in `infection.json`
  src/Container.php
  src/FileSystem/SourceFileCollector.php
  src/FileSystem/SourceFileFilter.php
  src/TestFramework/Coverage/ProxyTrace.php
  src/TestFramework/Coverage/Trace.php
  tests/benchmark/MutationGenerator/PartialTrace.php
  tests/e2e/Exclude_by_file_name/README.md
  tests/e2e/Exclude_by_file_name/composer.json
  tests/e2e/Exclude_by_file_name/expected-output.txt
  tests/e2e/Exclude_by_file_name/infection.json
  tests/e2e/Exclude_by_file_name/phpunit.xml
  tests/e2e/Exclude_by_file_name/src/Kernel.php
  tests/e2e/Exclude_by_file_name/src/SourceClass.php
  tests/e2e/Exclude_by_file_name/tests/SourceClassTest.php
  tests/phpunit/FileSystem/SourceFileCollectorTest.php
  tests/phpunit/FileSystem/SourceFileFilterTest.php
Labels: Bugfix

#1254 Move no-progress detection to the ConfigurationFactory
  src/Configuration/ConfigurationFactory.php
  src/Container.php
  src/Logger/LoggerFactory.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Fixtures/DummyCiDetector.php
  tests/phpunit/Fixtures/FakeCiDetector.php
  tests/phpunit/Logger/LoggerFactoryTest.php
Labels: BC break
