Repository infection/infection, pull requests merged in 2020-08, with the labels that each got.

#1299 Infection must return appropriate exit status when failing
  src/Command/BaseCommand.php
  src/Command/ConfigureCommand.php
  src/Command/RunCommand.php
Labels: Bugfix, Critical

#1310 TestLocator returns non-unique tests, but Mutation didn't know that
  src/Mutation/Mutation.php
  src/TestFramework/Coverage/JUnit/JUnitTestCaseTimeAdder.php
  tests/e2e/TimeoutSkipped/composer.json
  tests/e2e/TimeoutSkipped/expected-output.txt
  tests/e2e/TimeoutSkipped/infection.json
  tests/e2e/TimeoutSkipped/phpunit.xml.dist
  tests/e2e/TimeoutSkipped/src/SourceClass.php
  tests/e2e/TimeoutSkipped/tests/SourceClassTest.php
  tests/phpunit/Mutation/MutationTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestCaseTimeAdderTest.php
Labels: Bugfix, Critical

#1312 Improve JUnitTestCaseTimeAdderTest
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestCaseTimeAdderTest.php
Labels: Enhancement

#1313 Allow fractional values for timeout
  resources/schema.json
  src/Configuration/Configuration.php
  src/Configuration/Schema/SchemaConfiguration.php
  tests/phpunit/Configuration/ConfigurationAssertions.php
  tests/phpunit/Configuration/ConfigurationTest.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationTest.php
  tests/phpunit/Configuration/Schema/SchemaValidatorTest.php
Labels: Enhancement

#1306 Add mutator to remove shared cases
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Removal/SharedCaseRemoval.php
  tests/phpunit/Mutator/Removal/SharedCaseRemovalTest.php
Labels: Enhancement, Mutator
