Repository infection/infection, pull requests merged in 2020-11, with the labels that each got.

#1405 Add While expression mutator
  devTools/phpstan-src-baseline.neon
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/ZeroIteration/While_.php
  tests/phpunit/Mutator/ZeroIteration/While_Test.php
Labels: Mutator

#1410 Fix issue with order of keys in the config array
  composer.lock
  devTools/phpstan-tests.neon
  src/Mutator/MutatorResolver.php
  tests/phpunit/Mutator/MutatorResolverTest.php
Labels: Bugfix

#1416 Improve TestLocationBucketSorterTest
  tests/phpunit/TestFramework/Coverage/JUnit/TestLocationBucketSorterTest.php
Labels: DX

#1415 Use not included delimiter
  composer.lock
  src/Differ/DiffSourceCodeMatcher.php
  tests/phpunit/Differ/DiffSourceCodeMatcherTest.php
Labels: Bugfix

#1411 Add DoWhile expression mutator
  devTools/phpstan-src-baseline.neon
  resources/schema.json
  src/Mutator/Loop/DoWhile.php
  src/Mutator/ProfileList.php
  tests/phpunit/Mutator/Loop/DoWhileTest.php
Labels: Mutator

#1417 Use Composer 1.x on Travis
  .travis.yml
Labels: DX

#1424 Further simplify JUnitTestCaseTimeAdder
  src/TestFramework/Coverage/JUnit/JUnitTestCaseTimeAdder.php
Labels: Enhancement

#1423 Optimize NodeMutationGenerator
  devTools/phpstan-src-baseline.neon
  src/Mutator/NodeMutationGenerator.php
Labels: Enhancement, Performance

#1422 Lazify ProxyTrace with Deferred
  composer.json
  composer.lock
  src/TestFramework/Coverage/ProxyTrace.php
  src/TestFramework/Coverage/UncoveredTraceProvider.php
  src/TestFramework/Coverage/XmlReport/XmlCoverageParser.php
  tests/phpunit/Mutation/MutationGeneratorTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestExecutionInfoAdderTest.php
  tests/phpunit/TestFramework/Coverage/ProxyTraceTest.php
Labels: Enhancement

#1426 Improve MutationTestingRunner
  composer.json
  composer.lock
  src/Process/Runner/MutationTestingRunner.php
Labels: Performance

#1429 Add a Makefile rule to generate PHPStan baselines
  Makefile
Labels: DX

#1440 Add ConcatOperandRemoval mutator (fixes #1439)
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Removal/ConcatOperandRemoval.php
  tests/phpunit/Mutator/Removal/ConcatOperandRemovalTest.php
Labels: Mutator

#1442 Add Concat mutator
  resources/schema.json
  src/Mutator/Operator/Concat.php
  src/Mutator/ProfileList.php
  tests/phpunit/Mutator/Operator/ConcatTest.php
Labels: Mutator
