Repository infection/infection, pull requests merged in 2020-02, with the labels that each got.

#1031 Enhancement: Extract StrykerApiKeyResolver
  src/Environment/CouldNotResolveStrykerApiKey.php
  src/Environment/StrykerApiKeyResolver.php
  src/Logger/BadgeLogger.php
  src/Logger/LoggerFactory.php
  tests/phpunit/Environment/CouldNotResolveStrykerApiKeyTest.php
  tests/phpunit/Environment/StrykerApiKeyResolverTest.php
  tests/phpunit/Logger/BadgeLoggerTest.php
Labels: Enhancement

#1019 Use `infection/extension-installer` to automatically register Test Framework Adapters
  composer.json
  composer.lock
  src/Container.php
  src/TestFramework/Factory.php
  tests/phpunit/Fixtures/TestFramework/DummyTestFrameworkAdapter.php
  tests/phpunit/Fixtures/TestFramework/DummyTestFrameworkFactory.php
  tests/phpunit/TestFramework/FactoryTest.php
Labels: DX

#1046 Fix: Remove unused constants
  src/Logger/BadgeLogger.php
Labels: Bug

#1047 Enhancement: Extract BuildContextResolver
  src/Environment/BuildContext.php
  src/Environment/BuildContextResolver.php
  src/Environment/CouldNotResolveBuildContext.php
  src/Logger/BadgeLogger.php
  src/Logger/LoggerFactory.php
  tests/phpunit/Environment/BuildContextResolverTest.php
  tests/phpunit/Environment/BuildContextTest.php
  tests/phpunit/Environment/CouldNotResolveBuildContextTest.php
  tests/phpunit/Logger/BadgeLoggerTest.php
Labels: Enhancement

#1069 Fix: Keep rules and rule sets sorted in .php_cs.dist
  .php_cs.dist
Labels: Bug

#789 Enhancement: Allow specifying a few command line options via config
  resources/schema.json
  src/Configuration/ConfigurationFactory.php
  src/Configuration/Schema/SchemaConfiguration.php
  src/Configuration/Schema/SchemaConfigurationFactory.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationFactoryTest.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationTest.php
Labels: Enhancement

#1042 Allow the initial test suite to be skipped
  src/Command/InfectionCommand.php
  src/Configuration/Configuration.php
  src/Configuration/ConfigurationFactory.php
  src/Console/ConsoleOutput.php
  src/Container.php
  src/Engine.php
  src/Process/Coverage/CoverageRequirementChecker.php
  src/TestFramework/Coverage/CoverageDoesNotExistException.php
  tests/e2e/Skip_Initial_Tests/README.md
  tests/e2e/Skip_Initial_Tests/composer.json
  tests/e2e/Skip_Initial_Tests/expected-output_phpspec.txt
  tests/e2e/Skip_Initial_Tests/expected-output_phpunit.txt
  tests/e2e/Skip_Initial_Tests/infection-coverage/coverage-xml/SourceClass.php.xml
  tests/e2e/Skip_Initial_Tests/infection-coverage/coverage-xml/index.xml
  tests/e2e/Skip_Initial_Tests/infection-coverage/junit.xml
  tests/e2e/Skip_Initial_Tests/infection-coverage/phpspec-coverage-xml/SourceClass.php.xml
  tests/e2e/Skip_Initial_Tests/infection-coverage/phpspec-coverage-xml/index.xml
  tests/e2e/Skip_Initial_Tests/infection.json
  tests/e2e/Skip_Initial_Tests/phpspec.yml
  tests/e2e/Skip_Initial_Tests/phpunit.xml
  tests/e2e/Skip_Initial_Tests/run_tests.bash
  tests/e2e/Skip_Initial_Tests/spec/SourceClassSpec.php
  tests/e2e/Skip_Initial_Tests/src/SourceClass.php
  tests/e2e/Skip_Initial_Tests/tests/SourceClassTest.php
  tests/phpunit/Configuration/ConfigurationAssertions.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Configuration/ConfigurationTest.php
  tests/phpunit/ContainerTest.php
  tests/phpunit/Process/Coverage/CoverageRequirementCheckerTest.php
Labels: Feature

#1074 Accounting For Codeception Cest Tests In JUnit File.
  src/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageFactory.php
  tests/phpunit/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageFactoryTest.php
Labels: Enhancement
