Repository infection/infection, pull requests merged in 2020-12, with the labels that each got.

#1452 Allows to run infection in a path that contain spaces
  src/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilder.php
  tests/phpunit/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilderTest.php
Labels: Enhancement

#1457 Add PHP 8 specific NullSafe operator mutators
  composer.lock
  devTools/Dockerfile-php80-xdebug
  resources/schema.json
  src/Mutator/Operator/NullSafeMethodCall.php
  src/Mutator/Operator/NullSafePropertyCall.php
  src/Mutator/ProfileList.php
  tests/phpunit/Mutator/Operator/NullSafeMethodCallTest.php
  tests/phpunit/Mutator/Operator/NullSafePropertyCallTest.php
Labels: Mutator

#1458 Add a describe command
  src/Command/DescribeCommand.php
  src/Console/Application.php
  src/Mutator/Arithmetic/Plus.php
  src/Mutator/Definition.php
  tests/phpunit/Command/DescribeCommandTest.php
  tests/phpunit/Mutator/DefinitionTest.php
Labels: DX, Feature

#1460 Use unique values in `ignoreSourceCodeByRegex` to not waste resources
  src/Configuration/ConfigurationFactory.php
  src/Mutator/MutatorResolver.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Mutator/MutatorResolverTest.php
Labels: Bugfix
