Repository infection/infection, pull requests merged in 2020-03, with the labels that each got.

#604 Fix: Run php-cs-fixer on GitHub Actions
  .editorconfig
  .github/workflows/continuous-integration.yml
  .prettyci.composer.json
  README.md
Labels: Bug

#1104 Allow to configure ignore globally
  resources/schema.json
  src/Mutator/MutatorResolver.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationFactoryTest.php
  tests/phpunit/Mutator/MutatorResolverTest.php
Labels: Feature

#1102 Automatically install Test Framework adapter if needed
  composer.json
  composer.lock
  src/Command/InfectionCommand.php
  src/Container.php
  src/TestFramework/AdapterInstallationDecider.php
  src/TestFramework/AdapterInstaller.php
  tests/e2e/Adapter_Installer/README.md
  tests/e2e/Adapter_Installer/check_auto_install.expect
  tests/e2e/Adapter_Installer/composer.json
  tests/e2e/Adapter_Installer/infection.json
  tests/e2e/Adapter_Installer/phpunit.xml
  tests/e2e/Adapter_Installer/run_tests.bash
  tests/e2e/Adapter_Installer/src/SourceClass.php
  tests/e2e/Adapter_Installer/tests/SourceClassTest.php
  tests/e2e/Config_Framework/README.md
  tests/e2e/Config_Framework/composer.json
  tests/e2e/Config_Framework/expected-output.txt
  tests/e2e/Config_Framework/phpspec.yml
  tests/e2e/Config_Framework/run_tests.bash
  tests/e2e/Config_Framework/spec/SourceClassSpec.php
  tests/e2e/Config_Framework/src/SourceClass.php
  tests/e2e/Provide_Existing_Coverage/composer.json
  tests/e2e/Provide_Existing_Coverage/expected-output_phpspec.txt
  tests/e2e/Provide_Existing_Coverage/phpspec.yml
  tests/e2e/Provide_Existing_Coverage/run_tests.bash
  tests/e2e/Provide_Existing_Coverage/spec/SourceClassSpec.php
  tests/e2e/Skip_Initial_Tests/composer.json
  tests/e2e/Skip_Initial_Tests/expected-output_phpspec.txt
  tests/e2e/Skip_Initial_Tests/phpspec.yml
  tests/e2e/Skip_Initial_Tests/run_tests.bash
  tests/e2e/Skip_Initial_Tests/spec/SourceClassSpec.php
  tests/phpunit/AutoReview/ProjectCode/ProjectCodeProvider.php
  tests/phpunit/TestFramework/AdapterInstallationDeciderTest.php
Labels: DX, Enhancement

#1132 Drop support for PHP 7.2
  .travis.yml
  appveyor.yml
  composer.json
  composer.lock
  src/Mutator/Removal/ArrayItemRemovalConfig.php
  tests/e2e/Unconfigured/run_tests.bash
Labels: BC break

#1135 Enhancement: Use ondram/ci-detector to resolve build context
  composer.json
  composer.lock
  src/Environment/BuildContextResolver.php
  src/Environment/ChainBuildContextResolver.php
  src/Logger/BadgeLogger.php
  src/Logger/LoggerFactory.php
  tests/phpunit/Double/OndraM/CiDetector/ConfigurableEnv.php
  tests/phpunit/Environment/BuildContextResolverTest.php
  tests/phpunit/Environment/ChainBuildContextResolverTest.php
  tests/phpunit/Environment/TravisCiResolverTest.php
  tests/phpunit/Logger/BadgeLoggerTest.php
Labels: Enhancement

#1172 Optimize JUnit test lookups to stop on the first element
  src/TestFramework/Coverage/JUnit/JUnitTestExecutionInfoAdder.php
  src/TestFramework/Coverage/JUnit/JUnitTestFileDataProvider.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestFileDataProviderTest.php
Labels: Performance

#1177 Benchmark for JUnitTestCaseSorter::uniqueByTestFile
  devTools/phpstan-src.neon
  src/Process/Runner/MutationTestingRunner.php
  src/TestFramework/Coverage/JUnit/JUnitTestCaseSorter.php
  src/TestFramework/Coverage/JUnit/TestLocationBucketSorter.php
  tests/phpunit/Fixtures/TestFramework/PhpUnit/Coverage/JUnitTimes.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestCaseSorterTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/TestLocationBucketSorterTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/Builder/MutationConfigBuilderTest.php
Labels: Performance

#1193 Auto-discovery of the JUnit file
  src/Container.php
  src/TestFramework/Coverage/CoverageChecker.php
  src/TestFramework/Coverage/JUnit/JUnitReportLocator.php
  src/TestFramework/Coverage/JUnit/JUnitTestFileDataProvider.php
  tests/phpunit/TestFramework/Coverage/CoverageCheckerTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitReportLocatorTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestFileDataProviderTest.php
Labels: Enhancement

#1214 Make coverage path more tolerant
  src/Configuration/ConfigurationFactory.php
  src/Container.php
  src/TestFramework/Coverage/JUnit/JUnitReportLocator.php
  src/TestFramework/Coverage/XmlReport/IndexXmlCoverageLocator.php
  src/TestFramework/Coverage/XmlReport/IndexXmlCoverageParser.php
  src/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageTraceProvider.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/TestFramework/Coverage/CoverageCheckerTest.php
  tests/phpunit/TestFramework/Coverage/JUnit/JUnitReportLocatorTest.php
  tests/phpunit/TestFramework/Coverage/XmlReport/IndexXmlCoverageLocatorTest.php
  tests/phpunit/TestFramework/Coverage/XmlReport/IndexXmlCoverageParserTest.php
  tests/phpunit/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageTraceProviderTest.php
Labels: Feature

#1230 Cast Mutator's setting object to array before using
  src/Mutator/MutatorFactory.php
  src/Mutator/MutatorResolver.php
  tests/phpunit/Mutator/MutatorFactoryTest.php
Labels: Bugfix

#1233 U for uncovered
  src/Console/OutputFormatter/DotFormatter.php
  tests/phpunit/Console/OutputFormatter/DotFormatterTest.php
Labels: Awaiting Docs
