Repository infection/infection, pull requests merged in 2020-10, with the labels that each got.

#1334 Make Infection installable with Composer 2
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Console/Input/MsiParser.php
  src/Mutator/Removal/ArrayItemRemoval.php
  tests/phpunit/Console/ConsoleOutputTest.php
  tests/phpunit/PhpParser/FileParserTest.php
Labels: Bugfix, Critical

#1338 Check the length of schema node before using its values
  src/TestFramework/PhpUnit/Config/XmlConfigurationManipulator.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationManipulatorTest.php
Labels: Bugfix

#1342 Introduce YieldValue mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/ReturnValue/YieldValue.php
  tests/phpunit/Mutator/ReturnValue/YieldValueTest.php
Labels: Mutator

#1358 ArrayItemRemoval should not mutate lists
  src/Mutator/Removal/ArrayItemRemoval.php
  tests/phpunit/Mutator/Removal/ArrayItemRemovalTest.php
Labels: Bugfix

#1369 Improve Dockerfiles
  devTools/Dockerfile-php74-xdebug
  devTools/Dockerfile-php80-xdebug
  devTools/xdebug-coverage.ini
Labels: DX

#1371 Improve Makefile, E2E tests
  Makefile
  src/Console/Application.php
  tests/phpunit/AutoReview/Makefile/MakefileTest.php
  tests/phpunit/Console/E2ETest.php
Labels: DX

#1372 Use the same PHPUnit version for E2E tests as for Infection
  tests/e2e/Adapter_Installer/composer.json
  tests/e2e/Config_Bootstrap/composer.json
  tests/e2e/Configure/composer.json
  tests/e2e/Custom_tmp_dir/composer.json
  tests/e2e/Empty_Path/composer.json
  tests/e2e/Example_Test/composer.json
  tests/e2e/Exclude_Mutations_By_Regex/composer.json
  tests/e2e/Exclude_by_file_name/composer.json
  tests/e2e/Exec_Path/composer.json
  tests/e2e/Ignore_MSI_Zero_Mutations/composer.json
  tests/e2e/Initial_Configuration/composer.json
  tests/e2e/Memory_Limit/composer.json
  tests/e2e/Min_MSI/composer.json
  tests/e2e/Multiline_Statement/composer.json
  tests/e2e/Output_Stream/composer.json
  tests/e2e/PCOV_PHPUnit8/composer.json
  tests/e2e/PHPUnit93/composer.json
  tests/e2e/PHPUnit_Custom_Config_Dir/composer.json
  tests/e2e/PHPUnit_Hidden_Dependency/composer.json
  tests/e2e/PHPUnit_XSD_Validation/composer.json
  tests/e2e/PSR_0_Autoloader/composer.json
  tests/e2e/PhpUnit_Depends_Order/composer.json
  tests/e2e/Phpunit_Bat_Wrapper/composer.json
  tests/e2e/Profiles_Ignore_Combination/composer.json
  tests/e2e/Provide_Existing_Coverage/composer.json
  tests/e2e/Save_PHPUnit_Bootstrap_File/composer.json
  tests/e2e/Skip_Initial_Tests/composer.json
  tests/e2e/Source_Directories_Config/composer.json
  tests/e2e/Test_Framework_Options_Config/composer.json
  tests/e2e/Test_PHP_Options_Config/composer.json
  tests/e2e/TimeoutSkipped/composer.json
  tests/e2e/Variables_Order_EGPCS/composer.json
Labels: DX

#1370 Work around issue in Safe/DateTimeImmutable
  tests/phpunit/Logger/ConsoleLoggerTest.php
Labels: DX

#1376 Integration group annotation does not take comments
  tests/phpunit/FileSystem/Finder/TestFrameworkFinderTest.php
  tests/phpunit/FileSystem/Locator/RootsFileLocatorTest.php
  tests/phpunit/Mutator/IgnoreConfigTest.php
  tests/phpunit/TestFramework/Coverage/CoverageCheckerTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationManipulatorTest.php
Labels: DX

#1375 Request coverage reports with command line args
  src/TestFramework/AbstractTestFrameworkAdapter.php
  src/TestFramework/CommandLineBuilder.php
  src/TestFramework/PhpUnit/Adapter/PhpUnitAdapter.php
  src/TestFramework/PhpUnit/Adapter/PhpUnitAdapterFactory.php
  src/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilder.php
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpUnit/Config/XmlConfigurationManipulator.php
  tests/phpunit/TestFramework/PhpUnit/Adapter/PhpUnitAdapterTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilderTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationManipulatorTest.php
Labels: Enhancement

#1294 Refrain from adding filter tags if there are existing new-style coverage / include tags
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  tests/phpunit/Fixtures/Files/phpunit/phpunit_93.xml
  tests/phpunit/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilderTest.php
Labels: Enhancement

#1379 Trigger Travis CI deploy stage only for tagged builds
  .travis.yml
Labels: DX

#1378 Refactor InitialConfigBuilder
  phpunit.xml.dist
  src/TestFramework/PhpUnit/Adapter/PhpUnitAdapterFactory.php
  src/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilder.php
  src/TestFramework/PhpUnit/Config/XmlConfigurationManipulator.php
  src/TestFramework/PhpUnit/Config/XmlConfigurationVersionProvider.php
  tests/phpunit/TestFramework/PhpUnit/Config/Builder/InitialConfigBuilderTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationManipulatorTest.php
  tests/phpunit/TestFramework/PhpUnit/Config/XmlConfigurationVersionProviderTest.php
Labels: Bugfix, Feature

#1385 Add `ignoreSourceCodeByRegex` key for custom mutator definitions
  resources/schema.json
  tests/phpunit/Configuration/Schema/SchemaConfigurationFactoryTest.php
Labels: Bugfix

#1389 Add Flip Coalesce operator mutator
  resources/schema.json
  src/Mutator/Operator/FlipCoalesce.php
  src/Mutator/ProfileList.php
  tests/phpunit/Mutator/Operator/FlipCoalesceTest.php
Labels: Mutator

#1390 Add Ternary operator mutator
  resources/schema.json
  src/Mutator/Operator/Ternary.php
  src/Mutator/ProfileList.php
  tests/phpunit/Mutator/Operator/TernaryTest.php
Labels: Mutator

#1395 Implement UnwrapLtrim mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Unwrap/UnwrapLtrim.php
  tests/phpunit/Mutator/Unwrap/UnwrapLtrimTest.php
Labels: Mutator

#1398 Implement UnwrapStrShuffle mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Unwrap/UnwrapStrShuffle.php
  tests/phpunit/Mutator/Unwrap/UnwrapStrShuffleTest.php
Labels: Mutator

#1396 Implement UnwrapRtrim mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Unwrap/UnwrapRtrim.php
  tests/phpunit/Mutator/Unwrap/UnwrapRtrimTest.php
Labels: Mutator

#1399 Implement UnwrapStrRev mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Unwrap/UnwrapStrRev.php
  tests/phpunit/Mutator/Unwrap/UnwrapStrRevTest.php
Labels: Mutator

#1400 Implement UnwrapSubstr mutator
  resources/schema.json
  src/Mutator/ProfileList.php
  src/Mutator/Unwrap/UnwrapSubstr.php
  tests/phpunit/Mutator/Unwrap/UnwrapSubstrTest.php
Labels: Mutator
