Repository infection/infection, pull requests merged in 2022-01, with the labels that each got.

#1629 Replace `badge` logger with more advanced `stryker` logger
  infection.json
  resources/schema.json
  src/Configuration/Entry/Logs.php
  src/Configuration/Entry/StrykerConfig.php
  src/Configuration/Schema/SchemaConfigurationFactory.php
  src/Container.php
  src/Environment/StrykerApiKeyResolver.php
  src/Logger/BadgeLoggerFactory.php
  src/Logger/Http/StrykerCurlClient.php
  src/Logger/StrykerLogger.php
  src/Logger/StrykerLoggerFactory.php
  tests/phpunit/Configuration/ConfigurationAssertions.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Configuration/ConfigurationTest.php
  tests/phpunit/Configuration/Entry/LogsAssertions.php
  tests/phpunit/Configuration/Entry/LogsTest.php
  tests/phpunit/Configuration/Entry/StrykerConfigTest.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationFactoryTest.php
  tests/phpunit/Configuration/Schema/SchemaConfigurationTest.php
  tests/phpunit/Environment/StrykerApiKeyResolverTest.php
  tests/phpunit/Logger/FileLoggerFactoryTest.php
  tests/phpunit/Logger/Http/StrykerDashboardClientTest.php
  tests/phpunit/Logger/StrykerLoggerFactoryTest.php
  tests/phpunit/Logger/StrykerLoggerTest.php
Labels: BC break, DX, Feature

#1639 Remove `string` type declaration of parameter
  src/FileSystem/Finder/Iterator/RealPathFilterIterator.php
Labels: Bugfix

#1644 Correctly handle non UTF-8 characters in diff and process output for HTML logger
  src/Logger/Html/StrykerHtmlReportBuilder.php
  src/Logger/JsonLogger.php
  src/Str.php
  tests/phpunit/Logger/Html/StrykerHtmlReportBuilderTest.php
Labels: Bugfix

#1652 Create `MutationExecutionResult` instance with real path always, not mixed
  src/Logger/Html/StrykerHtmlReportBuilder.php
  src/Mutation/FileMutationGenerator.php
  tests/phpunit/Mutation/FileMutationGeneratorTest.php
Labels: Bugfix

#1654 Use merge-base (three dot diff) instead of direct diff for git-diff-ase (#1653)
  .github/workflows/mt-annotations.yaml
  src/Logger/GitHub/GitDiffFileProvider.php
  tests/phpunit/Logger/GitHub/GitDiffFileProviderTest.php
Labels: Feature

#1655 Use merge-base (three dot diff) instead of direct diff (#1653) (#1654)
  .github/workflows/mt-annotations.yaml
  src/Logger/GitHub/GitDiffFileProvider.php
  tests/phpunit/Logger/GitHub/GitDiffFileProviderTest.php
Labels: Feature
