Repository infection/infection, pull requests merged in 2023-05, with the labels that each got.

#1851 #857 Treat log paths as relative to config directory
  src/Configuration/ConfigurationFactory.php
  src/Logger/FileLogger.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
Labels: BC break, Bugfix

#1753 Add negation mutators
  psalm-baseline.xml
  resources/schema.json
  src/Mutator/Boolean/LogicalAndAllSubExprNegation.php
  src/Mutator/Boolean/LogicalAndNegation.php
  src/Mutator/Boolean/LogicalAndSingleSubExprNegation.php
  src/Mutator/Boolean/LogicalOrAllSubExprNegation.php
  src/Mutator/Boolean/LogicalOrNegation.php
  src/Mutator/Boolean/LogicalOrSingleSubExprNegation.php
  src/Mutator/Operator/ElseIfNegation.php
  src/Mutator/Operator/IfNegation.php
  src/Mutator/ProfileList.php
  src/Mutator/SimpleExpression.php
  src/Mutator/Util/AbstractAllSubExprNegation.php
  src/Mutator/Util/AbstractSingleSubExprNegation.php
  tests/phpunit/Mutator/BaseMutatorTestCase.php
  tests/phpunit/Mutator/Boolean/LogicalAndAllSubExprNegationTest.php
  tests/phpunit/Mutator/Boolean/LogicalAndNegationTest.php
  tests/phpunit/Mutator/Boolean/LogicalAndSingleSubExprNegationTest.php
  tests/phpunit/Mutator/Boolean/LogicalOrAllSubExprNegationTest.php
  tests/phpunit/Mutator/Boolean/LogicalOrNegationTest.php
  tests/phpunit/Mutator/Boolean/LogicalOrSingleSubExprNegationTest.php
  tests/phpunit/Mutator/Operator/ElseIfNegationTest.php
  tests/phpunit/Mutator/Operator/IfNegationTest.php
Labels: Mutator

#1853 During all "unwrap" functions, return the real values instead of values wrapped with `Node\Arg()` class
  src/Mutator/Unwrap/AbstractFunctionUnwrapMutator.php
  tests/phpunit/Mutator/Unwrap/UnwrapSubstrTest.php
Labels: Bugfix

#1854 Make PHPUnit 10.1 XML coverage report and test cases names with provider compatible with Infection and old format
  src/TestFramework/AbstractTestFrameworkAdapter.php
  src/TestFramework/CommandLineArgumentsAndOptionsBuilder.php
  src/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilder.php
  tests/phpunit/TestFramework/PhpUnit/CommandLine/ArgumentsAndOptionsBuilderTest.php
Labels: Bugfix
