Repository infection/infection, pull requests merged in 2025-07, with the labels that each got.

#2263 Smarter `Throw_` mutator
  src/Mutator/Operator/Throw_.php
  tests/phpunit/Mutator/Operator/Throw_Test.php
Labels: Mutator, Performance, Unproductive Mutator

#2278 TextFileLogger: add hints about different logfile options
  src/Logger/TextFileLogger.php
  tests/phpunit/Logger/TextFileLoggerTest.php
Labels: DX

#2280 Smarter `TrueValue`/`FalseValue` mutator
  src/Mutator/Boolean/FalseValue.php
  src/Mutator/Boolean/TrueValue.php
  tests/phpunit/Mutator/Boolean/FalseValueTest.php
  tests/phpunit/Mutator/Boolean/TrueValueTest.php
Labels: Mutator, Performance, Unproductive Mutator

#2284 Fix HTML report with `--static-analysis-tool=phpstan`
  src/Logger/Html/StrykerHtmlReportBuilder.php
  tests/phpunit/Logger/Html/StrykerHtmlReportBuilderTest.php
Labels: Bugfix, phpstan-integration

#2289 DX: Automatically determine git reference branch
  src/Configuration/ConfigurationFactory.php
  src/Differ/FilesDiffChangedLines.php
  src/Logger/GitHub/GitDiffFileProvider.php
  src/Mutator/NodeMutationGenerator.php
  src/Process/ShellCommandLineExecutor.php
  tests/phpunit/Logger/GitHub/GitDiffFileProviderTest.php
Labels: DX

#2300 MutationProcess timeout is based on test-execution time
  src/Process/Factory/MutantProcessContainerFactory.php
  tests/phpunit/Process/Factory/MutantProcessContainerFactoryTest.php
Labels: Performance

#2296 Add `ReturnRemoval` mutator
  devTools/phpstan-baseline.neon
  resources/schema.json
  src/Mutation/FileMutationGenerator.php
  src/Mutator/ProfileList.php
  src/Mutator/Removal/ReturnRemoval.php
  src/Mutator/Util/ReturnTypeHelper.php
  src/PhpParser/NodeTraverserFactory.php
  src/PhpParser/Visitor/NextConnectingVisitor.php
  src/PhpParser/Visitor/ReflectionVisitor.php
  src/Testing/BaseMutatorTestCase.php
  tests/e2e/PHPStan_Integration/expected-output.txt
  tests/e2e/Provide_Existing_Coverage/expected-output_phpunit.txt
  tests/e2e/Skip_Initial_Tests/expected-output_phpunit.txt
  tests/phpunit/Mutation/FileMutationGeneratorTest.php
  tests/phpunit/Mutator/DefinitionTest.php
  tests/phpunit/Mutator/Removal/ReturnRemovalTest.php
  tests/phpunit/Mutator/Util/ReturnTypeHelperTest.php
  tests/phpunit/PhpParser/NodeTraverserFactoryTest.php
  tests/phpunit/PhpParser/Visitor/NextConnectingVisitorTest.php
Labels: Mutator

#2326 Do not report unmatched ignored errors for PHPStan killer for a mutant
  src/StaticAnalysis/PHPStan/Process/PHPStanMutantProcessFactory.php
  tests/phpunit/StaticAnalysis/PHPStan/Process/PHPStanMutantProcessFactoryTest.php
Labels: Bugfix

#2336 Remove `--only-covered`; Introduce `--with-uncovered` instead
  .github/workflows/mt-annotations.yaml
  src/Command/RunCommand.php
  src/Configuration/Configuration.php
  src/Configuration/ConfigurationFactory.php
  src/Container.php
  tests/benchmark/Tracing/provide-traces-closure.php
  tests/e2e/Exclude_Mutations_By_Regex/run_tests.bash
  tests/e2e/Exec_Path/run_tests.bash
  tests/e2e/Multiline_Statement/expected-output.txt
  tests/e2e/Output_Stream/expected-output.txt
  tests/e2e/Profiles_Ignore_Combination/run_tests.bash
  tests/e2e/Provide_Existing_Coverage/run_tests.bash
  tests/e2e/Skip_Initial_Tests/run_tests.bash
  tests/e2e/YieldValue/run_tests.bash
  tests/phpunit/Configuration/ConfigurationAssertions.php
  tests/phpunit/Configuration/ConfigurationFactoryTest.php
  tests/phpunit/Configuration/ConfigurationTest.php
Labels: BC break

#2349 Cleanup PHPUnit result-cache files older than 30 days
  src/Event/Subscriber/CleanUpAfterMutationTestingFinishedSubscriber.php
  tests/phpunit/Event/Subscriber/CleanUpAfterMutationTestingFinishedSubscriberTest.php
Labels: Bugfix
